### ISSUE TITLE
Yet another fake complex antiderivative

### ISSUE THREAD

**Issue by ValZapod** [stblake/algebraic_integration#2]
Just like in 4a12cdbc4986982cb27dabf203d32e4a5b694a6e

Integrate[Cos[x]^2/Sqrt[Cos[x]^4 + Cos[x]^2 + 1], x] returns complex result since Integrate got IntegrateAlgebraic integrated in 13.0.0

((-1/3*I)*Sqrt[2]*Cos[x]^2*Log[(I - Tan[x]*Sqrt[3 + 3*Tan[x]^2 + Tan[x]^4])/(I + Tan[x]*Sqrt[3 + 3*Tan[x]^2 + Tan[x]^4])]*Sqrt[3 + 3*Tan[x]^2 + Tan[x]^4])/Sqrt[15 + 8*Cos[2*x] + Cos[4*x]]

Correct result is as said in FriCAS: https://www.12000.org/my_notes/ten_hard_integrals/inse5.htm#x8-410002.5.2

Of course it may be just a continuation of this bug somehow: https://mathematica.stackexchange.com/a/159410

**Comment by stblake** [comment]
IntegrateAlgebraic now improves on the FriCAS/AXIOM result: 

In[2348]:= IntegrateAlgebraic[1/((1 + u^2) Sqrt[3 + 3 u^2 + u^4]), u]

Out[2348]= 1/3 ArcTan[u Sqrt[3 + 3 u^2 + u^4]]

**Comment by ValZapod** [comment]
> improves

Your example works, but mine now is just unevaluated. BTW, the optimal antiderivative is here https://www.12000.org/my_notes/ten_hard_integrals/OLD_VERSION/inse5.htm#x6-50005 and clarification on how to solve is here: https://www.12000.org/my_notes/ten_hard_integrals/OLD_VERSION/paper.pdf
"It might appear at first that this is an elliptic integral; however, if we multiply and divide by
sin(x ), and then make the judicious substitution u= cos (x), we obtain the new integral"


Another such example, I have just found it IntegrateAlgebraic[(1 + x^2)^2/((1 - x^2)*(1 - 6*x^2 + x^4)^(3/4)), x]

Also this without FullSimplify now returns worse solution: Integrate[1/(a Sqrt[1 - (x/a)^2]), x] // FullSimplify
Example from here: https://mathematica.stackexchange.com/questions/174872/integral-that-yields-arctan-function-rather-than-arcsin?rq=1

**Comment by stblake** [comment]
Please note that IntegrateAlgebraic cannot directly solve this integral, however it can compute the following integral, that Mathematica needs as part of its recursive integration: 

Integrate`IntegrateAlgebraic[1/((1 + u^2) Sqrt[3 + 3 u^2 + u^4]), u]

This will not work until we push these changes to a future release of Mathematica. 


I am happy with the solution to this integral (from Euler): 

In[280]:= IntegrateAlgebraic[(1 + x^2)^2/((1 - x^2) (1 - 6 x^2 + x^4)^(3/4)), x]

Out[280]= 
ArcTan[(I + x)/(1 - 6 x^2 + x^4)^(1/4)] - 
 ArcTan[(1 - 6 x^2 + x^4)^(1/4)/(-I + x)] - 
 ArcTanh[(I + x)/(1 - 6 x^2 + x^4)^(1/4)] - 
 ArcTanh[(1 - 6 x^2 + x^4)^(1/4)/(-I + x)]

This one is unfortunate, but not much I can do at this point as I most definitely do not want to be using FullSimplify within IntegrateAlgebraic: 

In[283]:= Integrate[1/(a Sqrt[1 - (x/a)^2]), x]

Out[283]= Sqrt[-(1/a^2)] a Log[-Sqrt[-(1/a^2)] x + Sqrt[1 - x^2/a^2]]

**Comment by ValZapod** [comment]
> I am happy with the solution to this integral (from Euler):

So this is actually good that it is complex? I suppose it is not elementary otherwise??

>that Mathematica needs as part of its recursive integration:

So you are saying my example will be solved by Integrate now like in FriCAS but will need to wait next version of Mathematica to update this package? Okay, good enough for me.

**Comment by stblake** [comment]
So this is actually good that it is complex? I suppose it is not elementary otherwise??

I do not have a solution to this integral that does not contain Sqrt[-1], however I do not have a proof that one does not exist. 

So you are saying my example will be solved by Integrate now like in FriCAS but will need to wait next version of Mathematica to update this package? Okay, good enough for me.

Assuming my changes pass all regression tests then it will be included in a future release, yes.

**Comment by ValZapod** [comment]
> however I do not have a proof that one does not exist.

FriCAS also does not have it. It has a bug in this integral that I reported (https://github.com/fricas/fricas/issues/78), but there is a workaround that allows to trigger the unimplemented branch of Risch algo, which is a new one for me:

(1) -> setSimplifyDenomsFlag(true) 

(1) false Type: Boolean (2) -> integrate((1 + x^2)^2/((1 - x^2)*(1 - 6*x^2 + x^4)^(3/4)), x) 

> Error detected within library code: integrate: implementation incomplete (residue poly has multiple non-linear factors)

BTW, that integral was in presentation of 13.0 version here: https://youtu.be/D2BHp5hTrJo (on 3:57) and of course rised some eyebrows (mine), especially considering that on 4:09 the guy was using Chop to fix a bug with small +I result in NIntegrate, but he could have just used a different method, EvenOddSubdivision...

Anyway, will report more stiff if I will find it :) After all wolfram alpha is still on 12 version, so simple to check vs 13.

**Comment by ValZapod** [comment]
So this is the answer apparently  ```
- ATANH(2*x*(x^4 - 6*x^2 + 1)^(1/4)/(SQRT(x^4 - 6*x^2 + 1) + x^2 + 1))
 + ATAN(x/((x^4 - 6*x^2 + 1)^(1/4) + 1))
 - ATAN(((x^4 - 6*x^2 + 1)^(1/4) - 1)/x)

```
From Euler. https://scholarlycommons.pacific.edu/cgi/viewcontent.cgi?article=1688&context=euler-works

**Comment by stblake** [comment]
Like I wrote previously - I am happy with the answer currently provided by IntegrateAlgebraic.

**Comment by stblake** [comment]
Hi Valerii,

Thanks for your interest in improving IntegrateAlgebraic. As far as I can
tell, Mathematica does not call IntegrateAlgebraic in version 13.2

Here's one way to get an elementary solution in Mathematica (albeit with
the use of piecewise constants

(* Substitute u == Cos[x]: *)

In[12566]:= Eliminate[{Dt[y] == (Cos[x]^2 Dt[x])/Sqrt[
   Cos[x]^4 + Cos[x]^2 + 1], u == Cos[x], Dt[u == Cos[x]]}, {x, Dt[x]}]
Solve[%, Dt[y]]

During evaluation of In[12566]:= Eliminate::ifun: Inverse functions are
being used by Eliminate, so some solutions may not be found; use Reduce for
complete solution information.

Out[12566]= u^4 Dt[u]^2 + u^6 Dt[y]^2 == Dt[y]^2

Out[12567]= {{Dt[y] -> -((u^2 Dt[u])/Sqrt[1 - u^6])}, {Dt[y] -> (
   u^2 Dt[u])/Sqrt[1 - u^6]}}

(* Compute the resulting integral with IntegrateAlgebraic, the substitute
back and multiply by a piecewise constant to get a correct antiderivative:
*)

In[12568]:= IntegrateAlgebraic[u^2/Sqrt[1 - u^6], u]
% /. u -> Cos[x]
D[%, x]/(Cos[x]^2/Sqrt[Cos[x]^4 + Cos[x]^2 + 1]) // FullSimplify
% %%
D[%, x] - Cos[x]^2/Sqrt[Cos[x]^4 + Cos[x]^2 + 1] // Simplify

Out[12568]= 1/3 ArcTan[u^3/Sqrt[1 - u^6]]

Out[12569]= 1/3 ArcTan[Cos[x]^3/Sqrt[1 - Cos[x]^6]]

Out[12570]= -((Sqrt[1 + Cos[x]^2 + Cos[x]^4] Sin[x])/Sqrt[1 - Cos[x]^6])

Out[12571]= -((ArcTan[Cos[x]^3/Sqrt[1 - Cos[x]^6]] Sqrt[1 + Cos[x]^2 +
Cos[x]^4] Sin[x])/(3 Sqrt[1 - Cos[x]^6]))

Out[12572]= 0

Regarding your claim about integrals containing Sqrt[-1], that is not true.
Take, for example, the integral of 1/(x^2+1) the splitting field of the
resultants computed in the Risch algorithm are complex.

Cheers,

Sam

**Comment by ValZapod** [comment]
>Take, for example, the integral of 1/(x^2+1) the splitting field of the
resultants computed in the Risch algorithm are complex.

But the antiderivative does not contain I, it is just ArcTan[x].

And obviously we do not care about the antiderivative that have I inside functions that are actually just +C difference even if it is not obvious. (IT IS OFTEN not obvious at all, see e.g. my comment https://mathematica.stackexchange.com/questions/16885/how-to-evaluate-this-indefinite-integral-csc4x-sinx/16896#comment671095_16896, you should consider writing algorithm to see such things automatically!)

>Compute the resulting integral with IntegrateAlgebraic, then substitute
back and multiply by a piecewise constant to get a correct antiderivative

No way to code that into automatic system? Fricas did manage that. Maybe there is some bug in Mathematica's Risch that it thinks it is nonelementary.

**Comment by stblake** [comment]
In terms of logarithms its complex

In[237]:= ArcTan[x] // TrigToExp
Out[237]= 1/2 I Log[1 - I x] - 1/2 I Log[1 + I x]

I don't work for WRI, so I cannot comment on their Risch implementation
with any authority.

Cheers,

Sam
