### ISSUE TITLE
Not all Chebyshev-Zolotarev integrals can be handled

### ISSUE THREAD

**Issue by ValZapod** [stblake/algebraic_integration#5]
https://math.stackexchange.com/questions/3784897/how-to-apply-rischs-algorithm-to-int-fracx-sqrtx4-2x33x24x1-mat

Here it is:
`Integrate[x/Sqrt[x^4-2x^3+3x^2+4x+1], x]`

(While the classic example of now solvable Zolotarev integral is given on wikipedia page of Risch algorithm.)

Simplified Chebyshev algorithm is given here in the smaller answer: https://math.stackexchange.com/a/3933268

And citations here: https://math.stackexchange.com/a/4372918

**Comment by ValZapod** [comment]
@stblake LOL, this is just time sensetive, please increase IntegrateAlgebraicTimeConstraint to at least 20 or it just falls back!! https://mathematica.stackexchange.com/questions/267041/how-to-simplify-the-result-of-this-indefinite-integral/267052#267052
SetSystemOptions[
  "IntegrateOptions" -> {"IntegrateAlgebraicTimeConstraint" -> 20}];

Integrate[x/Sqrt[x^4 - 2 x^3 + 3 x^2 + 4 x + 1], x]

produces

1/3 ArcTanh[((1 + x) Sqrt[1 + 4 x + 3 x^2 - 2 x^3 + x^4])/x^3] + 
 ArcTanh[(-1 - 2 x + Sqrt[1 + 4 x + 3 x^2 - 2 x^3 + x^4])/x^2]

**Comment by stblake** [comment]
That time constraint is out of my control, however I don’t believe it should be modified. 

Sam

**Comment by ValZapod** [comment]
It is also possible fricas is more correct, it is certainly much faster and this type of integrals is supposed to be solved in logarithms: 

> 1/6 Log[-13 + 42 x^2 - 56 x^3 + 36 x^4 - 12 x^5 + 2 x^6 + 
>    Sqrt[1 + 4 x + 3 x^2 - 2 x^3 + 
>      x^4] (14 - 28 x + 24 x^2 - 10 x^3 + 2 x^4)]

Of course both give 0 after Simplify[D[f, x] - g].

**Comment by ValZapod** [comment]
Whatever you did it now prints (not yet in 13.2).
```
-(1/6) Log[
  13 - 42 x^2 + 56 x^3 - 36 x^4 + 12 x^5 - 2 x^6 + 
   Sqrt[1 + 4 x + 3 x^2 - 2 x^3 + 
     x^4] (14 - 28 x + 24 x^2 - 10 x^3 + 2 x^4)]
```

![image](https://user-images.githubusercontent.com/31514790/209267648-0927a4b1-4275-48d8-936b-a8ff5c7db7c3.png)
